openapi: 3.0.1
info:
  title: Genezis Storages
  description: "Сервис файловых хранилищ"
  version: 1.0.0
paths:
  /storage:
    post:
      tags:
        - storage
      summary: Добавление хранилища
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StorageRequest"
      responses:
        200:
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StorageResponse"
  /storage/{id}:
    get:
      tags:
        - storage
      summary: Получить данные хранилища
      parameters:
        - name: id
          in: path
          description: ID хранилища полученный при его добавлении
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StorageResponse"
    put:
      tags:
        - storage
      summary: Обновить данные хранилища
      parameters:
        - name: id
          in: path
          description: ID хранилища полученный при его добавлении
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StorageResponse"
    delete:
      tags:
        - storage
      summary: Удалить данные хранилища
      parameters:
        - name: id
          in: path
          description: ID хранилища полученный при его добавлении
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Успешный запрос
  /upload:
    post:
      tags:
        - upload
      summary: Загрузка файла
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/File"
      responses:
        200:
          description: successful operation

components:
  schemas:
    StorageRequest:
      type: object
      properties:
        storage_type:
          type: string
          description: Тип хранилища
          example: dropbox
        additional:
          type: object
    StorageResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        storage_type:
          type: string
          example: google
        additional:
          type: object
          description: Дополнительные данные для хранилища
    File:
      type: object
      properties:
        storage_id:
          type: integer
          format: int64
        path:
          type: string
          example: /lead_id/invoice.pdf
        file:
          type: string
          description: file to upload
          format: binary
